"""wwerw

Revision ID: 03f65cd8102d
Revises: e7bc880dbc92
Create Date: 2022-06-25 16:59:49.579995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03f65cd8102d'
down_revision = 'e7bc880dbc92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'marks', 'assignments', ['assi'], ['id'])
    # op.create_foreign_key(None, 'subjects', 'teacher', ['teacher'], ['tid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.drop_constraint(None, 'marks', type_='foreignkey')
    # ### end Alembic commands ###
