"""Initial migration.

Revision ID: 3172a5443503
Revises: 
Create Date: 2022-06-15 12:51:29.301106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3172a5443503'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('part', sa.Integer(), nullable=True))
    op.alter_column('assignments', 'maxnum',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('marks', 'mid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'marks', 'assignments', ['assi'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'marks', type_='foreignkey')
    op.alter_column('marks', 'mid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('assignments', 'maxnum',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('assignments', 'part')
    # ### end Alembic commands ###
